---
name: Repository Updater

on:
  repository_dispatch:
    types: ["update"]

jobs:
  publish:
    name: Publish app update
    runs-on: ubuntu-latest
    steps:
      - name: Run Repository Updater
        uses: hassio-addons/repository-updater@v2.0.1
        with:
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
